# Plugins (GitHub Pages supports these)
plugins:
  - jekyll-redirect-from

# Use Kramdown (with GitHub Flavored Markdown parser)
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true    # <-- allows Markdown inside <details>…</details>
  hard_wrap: false
  syntax_highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      stylesheet: /assets/css/custom.css
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: "ko"
    values:
      lang: ko
