title: it-docs
description: ""   # remove footer text
theme: minima
minima:
  skin: dark      # force dark skin

header_pages:
  - en/index.md
  - en/web/index.md
  - en/web/proposals/index.md
  - en/web/onboarding/index.md
  - ko/index.md
  - ko/web/index.md
  - ko/web/proposals/index.md
  - ko/web/onboarding/index.md

# Auto-apply front matter to everything under /en and /ko
defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: "ko"
    values:
      lang: "ko"

include:
  - assets/css/custom.css
  - _includes/lang-toggle.html
