# Plugins (GitHub Pages supports these)
plugins:
  - jekyll-redirect-from

url: "https://hankooktireusa.github.io"
baseurl: "/it-docs"
permalink: pretty

# Markdown engine settings
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false
  syntax_highlighter: rouge

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
      stylesheet: /assets/css/custom.css
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: "ko"
    values:
      lang: ko
